### PR TITLE
WIP tutorials

### PR DESCRIPTION
**Pull request by tlorans**
Hello,

Just to ping you and mention the fact that I'm working on a documentation based [your tutorial video](https://www.youtube.com/watch?v=xlieoONTLUs&t=602s). 

Still work in progress but I hope this is useful and not double work (as you've mentioned in the video that you were working on documentation already). :) 

Best regards,

Thomas

### CODE REVIEW

**Comment by essenciary** [comment]
Hey @tlorans - Great idea! That'd be awesome, any extra guides and docs are very useful!

I suggest: 

1/ follow up with @AbhimanyuAryan as he's been refactoring our guides using Pluto notebooks. This has some cool benefits including being able to test them and distribute them so the users can run them. 

2/ also the Stipple API has changed (not massively but in some important parts). We have new cool features like the @reactive macro, app events, a different workflow (no more global models), etc. Make it so that we can update the guides to the latest best practices.

**Comment by essenciary** [comment]
Is the PR ready to merge or still WIP?

**Comment by tlorans** [comment]
> Is the PR ready to merge or still WIP?

It is still WIP, will let you know once done :)

**Comment by tlorans** [comment]
> Hey @tlorans - Great idea! That'd be awesome, any extra guides and docs are very useful!
> 
> I suggest:
> 
> 1/ follow up with @AbhimanyuAryan as he's been refactoring our guides using Pluto notebooks. This has some cool benefits including being able to test them and distribute them so the users can run them.
> 
> 2/ also the Stipple API has changed (not massively but in some important parts). We have new cool features like the @reactive macro, app events, a different workflow (no more global models), etc. Make it so that we can update the guides to the latest best practices.

Really cool to get some tuto through Pluto!

Okay so I suggest:
1. I finish the « pure » transcript of the video in purely classic Documenter (should take 2 weeks I think);
2. Will try to change / update the parts in the tutorial concerned by the API changes;
3. Once done, can be used as a resource by @AbhimanyuAryan for some Pluto notebook guides.

Does it makes sens?

Best regards,
Thomas

**Pull request closed without merging**
