### PR TITLE
abstract model types for better redefinition behavior

### PR DESCRIPTION
**Pull request by hhaensel**
This PR introduces automatic generation of abstract model types, which take the defintions for `js_methods()`, `js_watch()`.
All (re)definitions of a modeltype are then subtypes of that new abstract type.

### Usage
Old style defintions
```julia
@reactive! mutual struct HHModel <: ReactiveModel
    a::R{Int} = 1
    b::R{Float64} = 2
end
```
are replaced with
```julia
@modeltype MyDashboard begin
    a::R{Int} = 1
    b::R{Float64} = 2
end
```
All the rest will just stay the same. `ReactiveTools` will work the same as well, except that now js_methods don't need to be redefined after a redefinition of the model.

### Internals

The `@modeltype` macro defines an abstract type `MyDashboard <: ReactiveType` and a concrete type `MyDashboard! <: MyDashboard`. As with `@reactive!` `MyDashboard!` is a constant which refers to the latest generated model type.

Note that `MyDashboard!` never needs to be used by the end user, because `init(MyDashboard)` will realise that `MyDashboard` is an abstract type and initialise `MyDashboard!` instead.

The advantage is that definitions like
```julia
js_methods(::MyDashboard) = """
    mysquare: function (x) {
        return x^2
    }
    myadd: function (x, y) {
        return x + y
    }
"""
```
will remain valid after a redefinition of the model type and don't need to be redefined.

### CODE REVIEW

**Comment by hhaensel** [comment]
This PR solves #143

**Comment by hhaensel** [comment]
- refactored all macros to support any kind of expressions
- added `@mix_in`, usage `@mix_in DownloadsMixin` or `@mix_in plot::PlotWithEvents`
- removed variable definition when executing macros
   - earlier `@in a = 12` failed because a was defined (`Html.a()`)
   - therefore definitions like `@in const date = today()` are not supported anymore
   - `@in x` is still supported and gives a warning when x is not defined

**Comment by hhaensel** [comment]
@essenciary I think I succeeded. `@reactive!` has been rewritten to apply the modes correctly.

I currently use `@vars`
```julia
@vars MyDashboard begin
    a::Real = 12
end
```
to define a type, but I'm not sure whether that's optimal. It's then difficult to do an `@add_vars MyDahboard <...> end`.
Maybe we introduce storages for all models ...?
Anyhow, it's much cleaner now, and we don't depend on Mixers anymore.

**Comment by hhaensel** [comment]
@add_vars needs a fix, sorry

**Comment by hhaensel** [comment]
fixed it and added `@add_vars` for models, e.g.
```julia
Stipple.@vars HH begin
    a::Int = 13, PRIVATE, NON_REACTIVE
    b::String = "Hello"
end
```
defines the model type and
```julia
Stipple.@add_vars HH begin
    a::Int = 13, PRIVATE
    b::String = "Hello"
end
```
expands the model, completely without a storage variable 😄 

I use almost the same code as for the `@mixins` in order to generate a storage from the type. Then I merge the storages and redefine the type. - I learned a lot about macro programming.
So, in principle, we could get rid of the storage and keep only the type cache. But I like the storage a lot, because it's more readable, if you want to inspect the storage. The storage now contains the `AUTOFIELDS`, that's the price for changing to the new private/readonly handling and getting rid of Mixers.

**Comment by hhaensel** [comment]
Finally, I implemented abstract models also for the REACTIVE_STORAGE and cleaned up a bit. Still some more cleanup is desireable, but it should be functional now.
I am wondering, whether we should unify the API a bit more, i.e.

```julia
@in s::String = "hello", NON_REACTIVE
```
rather than
```julia
@in non_reactive s::String = "hello"
```
That would allow us to also define
```julia
@in MyDashboard s::String = "hello"
```
and
```julia
@in MyDashboard s::String = "hello", NON_REACTIVE
```
It's not super important, as there is
```julia
@add_vars MyDashboard s::String = "hello"
```
and
```julia
@add_vars MyDashboard s::String = "hello", NON_REACTIVE
```

**Comment by essenciary** [comment]
From a UX and API design perspective, my goals were to: 
1/ allow users to tag their existing variables and expose them (make them reactive)
2/ hide away the concept and associated complexity of the reactive model 

So IMO, anything that has references to `MyDashboard` breaks these goals and it's more of an advanced, lower-level API.

**Comment by hhaensel** [comment]
I understand the goal of ReactiveTools. I thought, we'd support both the module-based approach as well as the model-based approach. I can well imagine a situation where I want to define several models in one module if these two models want to exchange information. Therefore I developed an API that would be very similar to the ReactiveTools API but that would take the name of the model. And I wanted to have a solution that would not setup as many model types as variables.

I admit that for such applications we don't necessarily need the `@in`, `@out` macros, because advanced developers could design their models with the `@vars` macro where everything is in one place.

Concerning non-reactive fields I'm hesitating. I like the syntax without `[]`, but the longer I think about it, I could also live without bare fields. They provide an easy way of establishing client_data with an initial value, e.g. password fields that should not be sent during typing but only upon a click. If we get rid of non_reactive fields, we should probably keep the `no_front_end_watcher` option.

So how do we go on here? Any good advice? What do you think about the main features:
- abstract models
- `@vars` and `@add_vars`
- `@mixin` and `@mix_in`
- access right storage in _modes field
- js `model.push(field)` method

**Comment by essenciary** [comment]
@hhaensel I understand. 

As a matter of principal it's OK to bundle more complex and low-level APIs for advanced users. There is the added complexity of maintaining this code but support for multiple models sounds useful. Setting up less models is definitely great. 

I think let's merge and see how it goes. If some of the advanced features are not used/popular and they make the code hard to maintain and debug, we can deprecate and remove or move into a separate package.

**Comment by hhaensel** [comment]
As I'm still not familiar with the total ReactiveTools API, could I ask you to test one of your more complicated new apps?
Or is there any test app we can run for testing?
Two more points:
- How far did you get in automated testing?
- Should we add a folder with examples of the new API to StippleDemos?

**Comment by essenciary** [comment]
@hhaensel Yes, I'll run some tests on a few demos we have. 

* end-to-end testing - we've had moderate initial success with porting Playwright using PyCall but eventually ran into some issues and didn't come up with a working solution. @AbhimanyuAryan can you share the status of this? 
* new demos - we also talked about it internally. Looping in @PGimenez and @cpalumbo to sync re demos and documentation.

**Comment by hhaensel** [comment]
> @hhaensel Yes, I'll run some tests on a few demos we have.

Cool, I've moved `parse_expression()` and `find_assignments()` to `reactive.jl` and delayed type generation in case there are no pages (yet). So there's some chance that less models are generated in case the models are defined before the pages.
You can always check how many models have been created by calling `subtypes(@type())`

> * end-to-end testing - we've had moderate initial success with porting Playwright using PyCall but eventually ran into some issues and didn't come up with a working solution. @AbhimanyuAryan can you share the status of this?

You may want to have a look at PythonCall instead of PyCall. Some things are solved in a nicer way there.


Finally, you may want run the tests with page updates. I think the abstract model should already do the handling automatically. Then we would only create a new model type when it is really used. For this just comment out the lines in the new `update_storage()` routine.
```julia
function update_storage(m::Module)
  clear_type(m)
  # isempty(Stipple.Pages._pages) && return
  # instance = @eval m Stipple.@type()
  # for p in Stipple.Pages._pages
  #   p.context == m && (p.model = instance)
  # end
end

```

**Comment by hhaensel** [comment]
Did you try with elevated user rights?
Did you try manually calling these steps on a python console?

**Comment by hhaensel** [comment]
Fixed two of the page macros and now everything is working fine even without the need of modifying the pages. Reloading triggers `route.action()`, which initialises the the model, which forces a new type beforehand.

**Comment by hhaensel** [comment]
`@init()` needed to be wrapped in an `@eval` in order to force the update the type.
After having[ fixed two issues in Genie/Html.jl](https://github.com/GenieFramework/Genie.jl/pull/601) everything runs smoothly and damn fast.

**Comment by hhaensel** [comment]
Some lines to demonstrate the efficiency of abstract models:

branch: master
```julia
julia> using Stipple, Stipple.ReactiveTools

julia> @in hh1 = "Hello"
"Hello"

julia> T = @type
var"##Main_ReactiveModel#314"

julia> client_data(::T) = Stipple.client_data(hh = "Hello World")
client_data (generic function with 2 methods)

julia> client_data(@model)
Dict{String, Any} with 1 entry:
  "hh" => "Hello World"

julia> @in hh2 = "world!"
"world!"

julia> client_data(@model)
ERROR: MethodError: no method matching client_data(::var"##Main_ReactiveModel#315")
Closest candidates are:
  client_data(::var"##Main_ReactiveModel#312") at REPL[4]:1
  client_data(::var"##Main_ReactiveModel#314") at REPL[13]:1
Stacktrace:
 [1] top-level scope
   @ none:4
```

branch: hh-abstract-models
```julia
julia> using Stipple, Stipple.ReactiveTools

julia> @in hh1 = "Hello"
"Hello"

julia> T = @type
[ Info: Main_ReactiveModel
Main_ReactiveModel

julia> client_data(::T) = Stipple.client_data(hh = "Hello World")
client_data (generic function with 1 method)

julia> client_data(@model)
Dict{String, Any} with 1 entry:
  "hh" => "Hello World"

julia> @in hh2 = "world!"
"world!"

julia> client_data(@model)
[ Info: Main_ReactiveModel
Dict{String, Any} with 1 entry:
  "hh" => "Hello World"
```

**Comment by hhaensel** [comment]
I think we should add macros for the js_methods etc., but otherwise the branch is probably ready to be merged.

**Comment by essenciary** [comment]
Agree, no benefit delaying for the macros, we can add later. Please merge when you see fit.

**Comment by hhaensel** [comment]
So did you do some tests from your end? Or is there any larger test for the new API?

**Comment by hhaensel** [comment]
Some fixes needed to be done. Now OscarsExplorer runs without errors both as is and and with the new `@vars` API.
So I think we can really merge this branch now.

**Pull request merged**
