### PR TITLE
interoperability for Stipple.JSONText and JSON.JSONText

### PR DESCRIPTION
**Pull request by hhaensel**
Only after [fixing handling of Stipple.JSONText in StipplePlotly](https://github.com/GenieFramework/StipplePlotly.jl/commit/54f15062fc81d6385753aceea300be5478d1fc21) I understood the root cause of the error.

It is that Stipple's definition of `JSONText` for JSON3 doesn't interoperate with JSON's definition, but PlotlyBase's JSON3-rendering is calling JSON behind the scenes. Therefore, `Stipple.JSONText("test")` is rendered as `"{\"s\": \"test\"}`
```julia
julia> JSON.json(Stipple.JSONText("test"))
"{\"s\":\"test\"}"
```
This PR adds all necessary methods to JSON3 and JSON to grant interoperability of the JSONText definitions so that
```julia
julia> JSON.json(Stipple.JSONText("test"))
"test"
```
Respective tests are added to `runtests.jl`
So if in future some component adds JSON3 rendering via a JSON fallback, we are save to use our `Stipple.JSONText`.

### CODE REVIEW

**Comment by essenciary** [comment]
@hhaensel is DataFrames a dependency of Stipple now? Is it just for testing? If it's for testing, last time I checked the best practice was to set up a distinct project in the `test/` folder and add test dependencies there.

**Comment by essenciary** [comment]
Same for `Test` - if it's not used by Stipple itself, it should go into the `test/` project. (Unless the best practice has changed recently).

**Comment by hhaensel** [comment]
AFAIK there are two ways of including packages for testing. One is defining a separate `Project.toml` in /test, as you said, the other - old school - variant is adding them to the `[extras]` section and listing their names under `targets`.
```julia
[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames", "JSON", "OffsetArrays"]
```
I took this practice from the [Extensions docs](https://pkgdocs.julialang.org/dev/creating-packages/#Backwards-compatibility) for the case that we want to support old julia versions which do not support extensions.
Re-reading the docs I found probably a way to get rid of the file copies without using, following this hint from the link above.
```julia
isdefined(Base, :get_extension) ? (using Contour) : (using ..Contour)
```
Let's see whether I can get that running.

**Comment by hhaensel** [comment]
> @hhaensel is DataFrames a dependency of Stipple now? Is it just for testing? If it's for testing, last time I checked the best practice was to set up a distinct project in the `test/` folder and add test dependencies there.

Here are the docs for [test-specific dependencies](https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies).

**Comment by essenciary** [comment]
> > @hhaensel is DataFrames a dependency of Stipple now? Is it just for testing? If it's for testing, last time I checked the best practice was to set up a distinct project in the `test/` folder and add test dependencies there.
> 
> Here are the docs for [test-specific dependencies](https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies).

Thanks for the link. I thought the "old" way was deprecated and was concerned that the dependencies would leak into the package installation (I haven't test exactly how and when are test deps installed with the current approach, hopefully only when running tests).

**Comment by hhaensel** [comment]
I think I remember, why the target-approach is used for Requires-compatibility. If you want to set compat entries for your weak dependencies old versions of Julia will complain if the packages are not listed either under [deps] or [extras].

**Comment by essenciary** [comment]
> I think I remember, why the target-approach is used for Requires-compatibility. If you want to set compat entries for your weak dependencies old versions of Julia will complain if the packages are not listed either under [deps] or [extras].

Hmmm... ok. I can't remember though, why do we have table rendering in Stipple? Shouldn't it be in StippleUI?

**Comment by hhaensel** [comment]
The answer is, we don't. The file StippleTablesExt.jl is mainly empty and never used. It's probably a left over from early testing.

**Comment by hhaensel** [comment]
@essenciary should we merge this? We could handle improved extension management in a separate PR.

**Comment by hhaensel** [comment]
Meanwhile, I released StipplePlotly 0.13.9 where rendering of Stipple.JSONText is at least fixed for the particular case of PlotlyBase
For a general solution, I would need the ok this PR.

**Comment by essenciary** [comment]
@hhaensel We'll run some tests to see if anything breaks. FYI @PGimenez

**Review by PGimenez — APPROVED** [review]
I tried a few apps and they all work as expected. I think we can merge.

**Comment by hhaensel** [comment]
Perfect! Don't trigger  new release yet, there's another PR in the pipeline.

**Pull request merged**
