### PR TITLE
Alternative rewrite of `@handlers`

### PR DESCRIPTION
**Pull request by hhaensel**
Alternative rewrite of `@handlers`

### CODE REVIEW

**Comment by hhaensel** [comment]
This is an alternative fix for #157 which addresses more details in code generation.
Fieldnames are not replaced if they occur in the list of variables, instead they are listed as variable names after `do` 
```julia
julia> @in i = 1;
julia> @in j = 2;
julia> @in k = 3;
julia> @macroexpand @onchange i begin
           println("The value of i is: ", i)
       end
quote
    #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:440 =#
    push!(__HANDLERS__, Expr[:(on(__model__.i) do i
      #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:435 =#
      begin
          #= REPL[38]:2 =#
          println("The value of i is: ", i)
      end
  end)]...)
end

julia> @macroexpand @onchangeany i, k begin
           println("The value of i, j is: ", i, ", ", j)
       end
quote
    #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:457 =#
    push!(__HANDLERS__, Expr[:(onany(__model__.i, __model__.k) do i, k
      #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:453 =#
      begin
          #= REPL[44]:2 =#
          println("The value of i, j is: ", i, ", ", __model__.j[])
      end
  end)]...)
end
```

**Comment by hhaensel** [comment]
I made `@onchange` take a deliberate number of fieldnames. `@onchangeany` is actually not necessary anymore in the new PR #159

**Comment by hhaensel** [comment]
So for a model with `i`, `j`, `k` we have
```julia
julia> @macroexpand @onchange i, k begin
           println("The value of i, j is: ", i, ", ", j)
       end
quote
    #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:448 =#
    push!(__HANDLERS__, Expr[:(onany(__model__.i, __model__.k) do i, k
      #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:442 =#
      begin
          #= REPL[53]:2 =#
          println("The value of i, j is: ", i, ", ", __model__.j[])
      end
  end)]...)
end
```

**Comment by hhaensel** [comment]
And
```julia
julia> @handlers begin
         @in i = 1
         @in j = 2
         @in k = 3
         @onchange i, j begin
           println("The value of i is: ", i)
           println("The value of k is: ", k)
         end
       end
__GF_AUTO_HANDLERS__ (generic function with 1 method)

julia> __HANDLERS__
1-element Vector{Expr}:
 :(onany(__model__.i, __model__.j) do i, j
      #= C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:442 =#
      begin
          #= REPL[55]:6 =#
          println("The value of i is: ", i)
          #= REPL[55]:7 =#
          println("The value of k is: ", __model__.k[])
      end
  end)
```

**Comment by essenciary** [comment]
@PGimenez will love this!

**Comment by essenciary** [comment]
> I made `@onchange` take a deliberate number of fieldnames. `@onchangeany` is actually not necessary anymore in the new PR #159

Awesome! We can add a deprecation warning and remove it before v1

**Comment by hhaensel** [comment]
So from my end this is ready for merging ...

**Comment by hhaensel** [comment]
The rewrite also allows to write
```julia
@clear
@in msg = ""
@onchange msg begin
    test(; msg)
end
```
Handlers are generated automatically just after the model type is generated (automatically)

**Comment by hhaensel** [comment]
@essenciary 
Do you think that
```julia
@handlers begin
    <...>
end
```
should empty the REACTIVE_STORAGE? Currently, it only empties the handler storage.

**Comment by hhaensel** [comment]
Just added some support for defining mixins with the new syntax.

**Comment by hhaensel** [comment]
@essenciary
I think with the latest changes the ReactiveTools API has become even a bit more comfortable.
My latest proposal for the API is to either use. Please feel free to propose other names.

```julia
@clear
@in a = 1
@in s = "hello"
@in hh = "test"

@onchange a begin
    println("a in 1:10: ", a in 1:10)
    println("a: ", a in 1:10)
end
```
or
```julia
@model begin
    @in a = 1
    @in s = "hello"

    @onchange a begin
        println("a in 1:10: ", a in 1:10)
        println("a: ", a in 1:10)
    end
end
```
The latter clears both storage and handlers, very similar to what `@handlers` does.
`@handlers` is still supported and can be used either like before
```julia
@handlers begin
    @in a = 1
    @in s = "hello"

    @onchange a begin
        println("a in 1:10: ", a in 1:10)
        println("a: ", a in 1:10)
    end
end
```
which leaves previous bindings untouched, or without arguments
```julia
@handlers
```
to force generation of `__GF_AUTO_HANDLERS__` after, just like `@type` for the storage.
`@clear_vars` and `@clear_handlers`clear storage and handlers respectively.

**Comment by AbhimanyuAryan** [comment]
@hhaensel mixin approach is very interesting. Can you give an example of mixin with Stipple?


```
macro define_mixin(mixin_name, expr)
  storage = @eval(__module__, Stipple.@var_storage($expr))
  delete!.(Ref(storage),  [:channel__, Stipple.AUTOFIELDS...])

  quote
      Base.@kwdef struct $mixin_name
          $(values(storage)...)
      end
  end |> esc
end
```

I only looked at Mixers.jl and thinking how can we tell user about it's use case and benefits in content of Stipple

**Comment by AbhimanyuAryan** [comment]
something is off

```julia
using GenieFramework
@genietools

@handlers begin
    @in idx = false
    @onchange idx begin
        @info "bid is placed"
        idx[] = false
    end
end

function ui()
    [
        card(
        [
            h1("Online Bidding 24x7 🌐", class="q-mx-auto")
            # h3("Select a range for your bet", [
            #     slider(1:5:100)
            # ])
            btn("place bid ⏳", color="red", class="float-right", @click("idx = true"))
        ])
    ]
end

@page("/", ui)

Server.isrunning() || Server.up()
```

error stack:

```
julia> include("app.jl")
[ Info: 2023-01-24 11:03:27 Watching ["C:\\Users\\aryan\\Documents\\GenieFrameworkDemos_NewAPI\\PlaceBid"]
ERROR: LoadError: MethodError: no method matching on(::var"#5#6", ::Bool)
Closest candidates are:
  on(::Any, ::AbstractObservable; weak, priority, update) at C:\Users\aryan\.julia\packages\Observables\PHGQ8\src\Observables.jl:356
Stacktrace:
  [1] __GF_AUTO_HANDLERS__(__model__::var"##Main_ReactiveModel!#312")
    @ Main C:\Users\aryan\.julia\dev\Stipple\src\ReactiveTools.jl:631
  [2] |>(x::var"##Main_ReactiveModel!#312", f::typeof(__GF_AUTO_HANDLERS__))
    @ Base .\operators.jl:911
  [3] top-level scope
    @ C:\Users\aryan\.julia\dev\Stipple\src\ReactiveTools.jl:447
  [4] eval
    @ .\boot.jl:368 [inlined]
  [5] (::var"#7#8")()
    @ Main C:\Users\aryan\.julia\dev\Stipple\src\ReactiveTools.jl:699
  [6] #invokelatest#2
    @ .\essentials.jl:729 [inlined]
  [7] invokelatest
    @ .\essentials.jl:726 [inlined]
  [8] Page(route::String; view::typeof(ui), model::var"#7#8", layout::String, context::Module, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Stipple.Pages C:\Users\aryan\.julia\dev\Stipple\src\Pages.jl:56
  [9] top-level scope
    @ C:\Users\aryan\.julia\dev\Stipple\src\ReactiveTools.jl:686
 [10] include(fname::String)
    @ Base.MainInclude .\client.jl:476
 [11] top-level scope
    @ REPL[1]:1
in expression starting at C:\Users\aryan\Documents\GenieFrameworkDemos_NewAPI\PlaceBid\app.jl:25
```

**Comment by hhaensel** [comment]
I know, I'm working on it.

**Comment by hhaensel** [comment]
@AbhimanyuAryan 
I would be happy if yoou could do some testing.

With the latest changes you can do

```julia
@handlers begin
    @out message = ""
    @private df = DataFrame()
    @out! table = DataTable()
    @onchange isready begin
        @show "App is loaded"
    end
    @onchange df table = DataTable(df)
end
```
but also 
```julia
@model begin
    @out message = ""
    @private df = DataFrame()
    @out! table = DataTable()
    @onchange isready begin
        @show "App is loaded"
    end
    @onchange df table = DataTable(df)
end
```
in order to also clear the input variables beforehand.
Furthermore, generic model types are supported:
```julia
@model MyModel begin
    @out message = ""
    @private df = DataFrame()
    @out table = DataTable()
    @onchange isready begin
        @show "App is loaded"
    end
    @onchange df table = DataTable(df)
end mymodel_handlers
```
Note that in case of defining generic models (and their handlers) I chose to not define identical variable names in the current name space.

@essenciary, @AbhimanyuAryan 
I am still not a friend of defining a variable with the reactive storage macros. E.g. the first command will fail at the REPL:
```julia
julia> @handlers begin
           @out message = ""
           @private df = DataFrame()
           @out table = DataTable()
           @onchange isready begin
               @show "App is loaded"
           end
           @onchange df table = DataTable(df)
       end
ERROR: cannot assign a value to variable Html.table from module Main
Stacktrace:
 [1] macro expansion
   @ REPL[7]:4 [inlined]
 [2] top-level scope
   @ C:\Users\m136270\.julia\dev\Stipple\src\ReactiveTools.jl:533
```
I don't see a benefit from this behaviour. If peopple want their existing variables to be contained in the model, they could still call `@in myvariable`.
@essenciary could you show me an MWE how this behavior is used?

**Comment by AbhimanyuAryan** [comment]
@hhaensel I am on it. Testing and reading the changes :)

**Comment by AbhimanyuAryan** [comment]
ok looks like button `click` is busted. Code to reproduce. In all three cases you process without `@handlers` and `@models` and with them

```
using GenieFramework
@genietools

@in idx = false
@onchange idx begin
    @info "bid is placed"
    idx[] = false
end

function ui()
    [
        card(
        [
            h1("Online Bidding 24x7 🌐", class="q-mx-auto")
            h3("Select a range for your bet", [
                slider(1:5:100)
            ])
            btn("place bid ⏳", color="red", @click("idx = true"))
        ])
    ]
end

@page
Server.isrunning() || Server.up()
```


```
┌ Error: 2023-01-24 16:19:08 Error attempting to invoke handler 3 for field Reactive{Bool}(Observable(true), 1, false, false, "C:\\Users\\aryan\\Documents\\GenieFrameworkDemos_NewAPI\\PlaceBid\\app.jl:5") with value true
└ @ Stipple C:\Users\aryan\.julia\dev\Stipple\src\stipple\mutators.jl:36
┌ Error: 2023-01-24 16:19:08 MethodError(setindex!, (true, false), 0x0000000000007f5b)
└ @ Stipple C:\Users\aryan\.julia\dev\Stipple\src\stipple\mutators.jl:37
```

**Comment by AbhimanyuAryan** [comment]
also since are talking about `@click` now. I would like to bring this up that `onbutton` handler is also busted on masters

https://github.com/GenieFramework/Stipple.jl/blob/2d3ac80483cd1d33f836fc7b7aac678aca73c749/src/ReactiveTools.jl#L446-L457

crashes at `@process_handler_input()`

**Comment by hhaensel** [comment]
I still favour a renaming of the storage macros in the following way:

`@in myvar = 10` inserts the variable in the storage without defining it in the current name space
`@in! myvar = 10` inserts the variable in the storage and defines `myvar` in the current name space

I know that this is breaking, but I think it will only have effect on how ReactiveTools is used at the REPL. Functional apps are most probably not affected. Furthermore, names like `table` don't shadow the StippleUI functions and keywords like `in` are allowed.

**Comment by hhaensel** [comment]
- Not sure whether I understand where useless variables are created.
- Tagging of existing variables would work as before `@in my_existing_var`

Only thing that would change is.
```julia
julia> myvar
ERROR: UndefVarError: myvar not defined

julia> @in myvar = 10
10

julia> myvar
ERROR: UndefVarError: myvar not defined

julia> @in! myvar = 10
10

julia> myvar
10
```
Currently it's the other way around and we're getting errors at the REPL if we use `@in used_var` with names that are already in use. From my point of view, `@in myvar` should be the standard use case and not lead to errors.

- What would you expect that `@handlers` does? Should it define all variables in the current name space?
```julia
julia> @handlers begin
  myvar = 10
  @onchange myvar begin
    println(myvar)
  end
end

julia> myvar
10
```

**Comment by essenciary** [comment]
Yes, I understand the proposal. The use case I mention is that where a user augments an existing Julia app/codebase to build a UI. In this case they "tag" existing variables from their original code.

**Comment by hhaensel** [comment]
I'd love to see such piece of non-Stipple code and how it's augmented with the existing API.
Do you have an example that you can share?

**Comment by AbhimanyuAryan** [comment]
strange `@onchange` works fine now. Nothing is pushed as I can see

**Comment by PGimenez** [comment]
I don't think we have any examples of that, but I think it'd look something like this...

In the [German Credits tutorial](https://genieframework.com/blog/how-to-quickly-turn-your-julia-code-into-a-web-app-with-genie-builder/#1-writing-the-data-analysis-code), we first write the data analysis code and add some lines to test the functions. We could output the results like this

```julia
  # testing the functions
 using CSV
 data = CSV.File("german_credits.csv") |> DataFrame
 @out gbcs = good_bad_credits_stats(data)
 @out caa = credit_age_amount(data, good_rating=true)
 @out cba = credit_no_by_age(data, good_rating=true)
```

and then define the UI in `ui.jl`. With a minimal `app.jl`, no user code would need to be written there. That is, unless we want to update the values of the variables at some point with an `@onchange`

**Comment by hhaensel** [comment]
Thank you, @PGimenez . For this example we wouldn't need defining behaviour, though.
I'd like to better understand the advantage of local variable copies of the model fields.
I'm sure there is one, it's just that I don't grasp it.

**Comment by AbhimanyuAryan** [comment]
this new api feels very clean. Not a fan of using `@model` / `@handlers` :( 

newapi

**Comment by AbhimanyuAryan** [comment]
@hhaensel any downsides of throwing reactive vars in global scope vs wrapping them in `@handlers`?

**Comment by hhaensel** [comment]
> @hhaensel any downsides of throwing reactive vars/`events handers` in global scope vs wrapping them in `@handlers`? Except that models calls `delete_bindings` by default?

No, there is no difference between using the wrappers `@model` or `@handlers` except the clearing of the respective storage.
Currently any usage of `@in` will create a variable in the current name space with the same name as the model field, even when using the wrappers.

The comfortable thing with the wrappers is that changes during development are immediately reflected.
If you have
```julia
@model begin
    @out message = ""
    @private df = DataFrame()
    @out! table = DataTable()
    @onchange isready begin
        println("App is loaded")
    end
    @onchange df table = DataTable(df)
end
```
and you append a variable, say
```julia
@model begin
    @out message = ""
    @private df = DataFrame()
    @out! table = DataTable()
    @onchange isready begin
        println("App is loaded")
    end
    @onchange df table = DataTable(df)
    @in newvar = 10
end
```
a succeeding call of `@init` results in
```julia
julia> propertynames(@init())
(:channel__, :modes__, :isready, :isprocessing, :message, :df, :table, :newvar)
```
This is not the case if you change a linear script without wrappers. A changed variable will only be appended, even if you have a `@clear` macro at the begining because Revise only executes/rewinds the portion of the code that has changed.

So if you are developping a project the advantage of wrappers is big.

Moreover, with the latest commit you can now use all macro calls with a modeltype, e.g.
```julia
@model MyModel begin
    @out message = ""
    @private df = DataFrame()
    @out! table = DataTable()
    @onchange isready begin
        println("App is loaded")
    end
    @onchange df table = DataTable(df)
    @in newvar = 10
end
```
but also
```julia
@in MyModel newvar = 4
```

**Comment by essenciary** [comment]
> Thank you, @PGimenez . For this example we wouldn't need defining behaviour, though.
> I'd like to better understand the advantage of local variable copies of the model fields.
> I'm sure there is one, it's just that I don't grasp it.

@hhaensel it boils down to a very common question in Genie: "how do I add a web UI to my existing app, vs creating an app from scratch?". And in the first release I started from existing code and tagged existing variables. In this case, obviously, the variable needs to be returned so the user code keeps working.

**Comment by essenciary** [comment]
@hhaensel what is the difference between `@handlers` and `@model` then? (I don't like the word `model` as it doesn't mean anything for the users in the current API, the model is just an implementation detail, not an API for the users).

**Comment by hhaensel** [comment]
`@handlers(expr)` clears `Stipple.HANDLERS[__module__]`

`@model(expr)` clears `Stipple.REACTIVE_STORAGE[__module__]`

**Comment by hhaensel** [comment]
We could rename `@model` to `@app` ...?

**Comment by AbhimanyuAryan** [comment]
> We could rename `@model` to `@app` ...?

I like `@app` better because even in vue we do that `const = createApp({ // all reactive models and properties })` so it's logically consistent and makes sense

**Comment by essenciary** [comment]
@app sounds great. 

My suggestions is to have a call between the 4 of us (@hhaensel @AbhimanyuAryan @PGimenez and I) to go over the API together, clean it up, discuss and introduce potential breaking changes, document the code, agree on recommended user flows, etc. Maybe 1.5h - next week?

**Comment by hhaensel** [comment]
> We should have a chat to cleanup the public API, with @PGimenez too as he's been using the API a lot. For instance we export a lot of macros and some are definitely not user-facing image

Looking forward to the chat 🚀 
Let me already explain my idea behind the latest changes of the API

`Stipple.ReactiveTools` brings two things; implicit (invisible) model types and a new API. The aim of the PR is to modernize the old API (mainly replace `@reactive` by `@vars`) and to make both APIs available for both implicit and explicit model types.

Why? Explicit models are interesting for two reasons
1. apps that have been written with the old API should be easily adaptable to the Stipple syntax
2. if model types can be used as mixins there is no need for another API

The current status is as follows.

```julia
@app begin
  @in i = 10
  @out s = "Hello"
  @private sh = "Psst!"
  @onchange i, s begin
    println("i: $i, j: $j")
  end
  @event updatefiles begin
    files = readdir(FILE_PATH)
  end
end
```
With very much the same snippet we can also define an explicit model type
```julia
@app MyModel begin
  @in i = 10
  @out s = "Hello"
  @private sh = "Psst!"
  @onchange i, s begin
    println("i: $i, j: $j")
  end
  @event updatefiles begin
    files = readdir(FILE_PATH)
  end
end mymodel_handlers
```
Note that you have to define the name of the handers function, which is `handlers` by default.

In the old API this would read
```julia
@vars MyModel begin
  i = 10
  s = "Hello"
  sh = "Psst!", PRIVATE
end

function mymodel_handlers(model)
  onany(model.i, model.j) do i,  j
    println("i: $i, j: $j")
  end
end

function Base.notify(model::MyModel, ::Val{:updatefiles}, @nospecialize(event))
  begin
      files = readdir(FILE_PATH)
  end
end
```
The good thing is, the `@vars` and `@handlers`syntax can also be combined for both explicit and implicit model types:
```julia
@vars begin
  i = 10
  s = "Hello"
  sh = "Psst!", PRIVATE
end

@handlers
  @onchange i, s begin
    println("i: $i, j: $j")
  end
end
```
and
```julia
@vars MyModel begin
  i = 10
  s = "Hello"
  sh = "Psst!", PRIVATE
end

@handlers MyModel begin
  @onchange i, s begin
    println("i: $i, j: $j")
  end
end mymodel_handlers
```
For experimenting and for final rollout we still have the wrapperless version
```julia
@in i = 10
@out s = "Hello"
@private sh = "Psst!"
@onchange i, s begin
  println("i: $i, j: $j")
end
```
Finally we have a new possibility of using model types as mixins
```julia
julia> @app MyModel begin
         @in i = 10
         @out s = "Hello"
         @private sh = "Psst!"
         @onchange i, s begin
           println("i: $i, j: $j")
         end
       end
(MyModel, handlers)

julia> @app begin
         @in i = 10
         @out s = "Hello"
         @private sh = "Psst!"
         @mix_in mix_::MyModel
         @onchange i, s begin
           println("i: $i, j: $j")
         end
       end
__GF_AUTO_HANDLERS__ (generic function with 1 method)

julia> REACTIVE_STORAGE[Main]
LittleDict{Symbol, Expr, Vector{Symbol}, Vector{Expr}} with 10 entries:
  :channel__    => :(channel__::String = Stipple._deepcopy("NDRPCXMVAEZQKQLWZOVFCUQJKBTOKDSW"))
  :modes__      => :(modes__::Stipple.LittleDict{Symbol, Any} = LittleDict{Symbol, Any, Vector{Symbol}, Vector{Any}}())
  :isready      => :(isready::Reactive{Bool} = Stipple._deepcopy(Reactive{Bool}(Observable(false), 1, false, false, "")))
  :isprocessing => :(isprocessing::Reactive{Bool} = Stipple._deepcopy(Reactive{Bool}(Observable(false), 1, false, false, "")))
  :i            => :(i::R{Int64} = R(10, 1, false, false, "REPL[28]:2"))
  :s            => :(s::R{String} = R("Hello", 4, false, false, "REPL[28]:3"))
  :sh           => :(sh::R{String} = R("Psst!", 2, false, false, "REPL[28]:4"))
  :mix_i        => :(mix_i::Reactive{Int64} = Stipple._deepcopy(Reactive{Int64}(Observable(10), 1, false, false, "")))
  :mix_s        => :(mix_s::Reactive{String} = Stipple._deepcopy(Reactive{String}(Observable("Hello"), 4, false, false, "")))
  :mix_sh       => :(mix_sh::Reactive{String} = Stipple._deepcopy(Reactive{String}(Observable("Psst!"), 2, false, false, "")))
```
Currently, handlers and events are not mixed, but maybe I'll find a way to do this in the future.
One final thought: We could make `@vars` also understand the new API syntax.

**Comment by hhaensel** [comment]
> using GenieFramework
> @genietools
> 
> `@in` idx = false
> `@onchange` idx begin
>     `@info` "bid is placed"
>     idx[] = false
> end
> 
> function ui()
>     [
>         card(
>         [
>             h1("Online Bidding 24x7 🌐", class="q-mx-auto")
>             h3("Select a range for your bet", [
>                 slider(1:5:100)
>             ])
>             btn("place bid ⏳", color="red", `@click`("idx = true"))
>         ])
>     ]
> end
> 
> @page
> Server.isrunning() || Server.up()

It's not about the `@click` macro, it's about correct usage of assignment. The best way out is to use `@onbutton`, but if you stick to `@onchange` you need to assign without `[]` and you have to abort the event handler `idx` is false `idx || return`, otherwise you'll end up with an infinite loop.
```julia
using GenieFramework
@genietools

@app begin
    @in idx = false
    @onchange idx begin
        idx || return
        notify(__model__, "Classical bid is placed", :positive, icon = :tag_faces, caption = "I bet you didn't know that")
        @info "bid is placed"
        idx = false
    end

    @onbutton idx begin
        # with the latest changes in the branch hh-handlers
        @notify("Bid is placed", :positive, icon = :tag_faces, caption = "I bet you didn't know that")
        # or
        @notify "Bid is not placed" :warning icon = :tag_faces caption = "I bet you didn't know that"
    end
end

function ui()
    [
        card(
        [
            h1("Online Bidding 24x7 🌐", class="q-mx-auto")
            h3("Select a range for your bet", [
                slider(1:5:100)
            ])
            btn("place bid ⏳", color="red", @click(:idx))
        ])
    ]
end

@page("/", ui)
up()
```
You could do `idx[!] = false` to prevent notifying `__model__.idx` but then you would not reset the button on the client side to false and you would not be able to re-press the button...

**Comment by hhaensel** [comment]
For a nicer UI I'd recommend
```julia
function ui()
    [
        card(class = "q-pa-lg",
        [
            h1(row(class = "container items-center", [
                icon(class = "text-blue", "language")
                cell(class = "q-ml-sm", "Online Bidding 24x7")
            ]))
            h3(cell(class = "", [
                "Select a range for your bet"
                slider(1:5:100, :betrange)
            ]))
            btn(class = "", "place bid", icon = "hourglass_top", color="red", @click(:idx))
        ])
    ]
end
```
image

**Comment by AbhimanyuAryan** [comment]
> ```julia
> idx || return
>         notify(__model__, "Classical bid is placed", :positive, icon = :tag_faces, caption = "I bet you didn't know that")
>         @info "bid is placed"
>         idx = false
> ```

thanks helmut I mostly use `onbutton` macro but I pulled this code from GB. I wasn't aware about the new changes made regarding `Base.notify` thanks for code ❤️

**Comment by hhaensel** [comment]
`notify(model::ReactiveModel, args...)` sends messages to the web page. You find some details in the doc string. It calls Quasar's notify function which is well documented in the Quasar docs.

**Comment by hhaensel** [comment]
> 



> > ```julia
> > idx || return
> >         notify(__model__, "Classical bid is placed", :positive, icon = :tag_faces, caption = "I bet you didn't know that")
> >         @info "bid is placed"
> >         idx = false
> > ```
> 
> I wasn't aware about the new changes made regarding `Base.notify` thanks for code ❤️

The changes to `Base.notify()` are not so new. But the macro is. I just wrote it to come up with a nicer answer.

**Comment by AbhimanyuAryan** [comment]
> > 
> 
> > > ```julia
> > > idx || return
> > >         notify(__model__, "Classical bid is placed", :positive, icon = :tag_faces, caption = "I bet you didn't know that")
> > >         @info "bid is placed"
> > >         idx = false
> > > ```
> > 
> > 
> > I wasn't aware about the new changes made regarding `Base.notify` thanks for code ❤️
> 
> The changes to `Base.notify()` are not so new. But the macro is. I just wrote it to come up with a nicer answer.

aah ok it's $q.notify from stipple demos. I thought it's some new. Cool Cool :)

**Comment by AbhimanyuAryan** [comment]
out of curiosity when are we planning to merge this PR to master?

**Comment by hhaensel** [comment]
@essenciary proposed a conference call to finalise things. From my end the changes can be merged. They are not breaking - well I removed some macros from export like `@type`, `@rstruct` to have a cleaner name space.
All other changes can probably be made without a big PR.

**Comment by essenciary** [comment]
@hhaensel the call is more to discuss the mid/long term direction of the APIs and packages, plan some deprecations and breaking releases to cleanup, documentation, etc - so not a blocker for merging the PR. Please merge when deemed stable. I've seen the names updates for macros, they're nice! 
I'll follow up in private to schedule the call.

**Comment by AbhimanyuAryan** [comment]
ok @hhaensel let me test this on 1.9 and 1.10-dev and then we will merge it ✔️ should be done by tomorrow morning

**Comment by AbhimanyuAryan** [comment]
@hhaensel looks good on 1.9 we should merge it. However failed to precompile genie on 1.10 some issues. But that's different issue. It's should be safe to merge to master with Genie 5.15 deps

**Comment by hhaensel** [comment]
It's released 😃 as Stipple v0.25.19

**Comment by AbhimanyuAryan** [comment]
> For a nicer UI I'd recommend
> 
> ```julia
> function ui()
>     [
>         card(class = "q-pa-lg",
>         [
>             h1(row(class = "container items-center", [
>                 icon(class = "text-blue", "language")
>                 cell(class = "q-ml-sm", "Online Bidding 24x7")
>             ]))
>             h3(cell(class = "", [
>                 "Select a range for your bet"
>                 slider(1:5:100, :betrange)
>             ]))
>             btn(class = "", "place bid", icon = "hourglass_top", color="red", @click(:idx))
>         ])
>     ]
> end
> ```
> 
> image

@hhaensel what bother me more and I don't what causes this....Is this slider getting invisible. Looks broken. Are you aware of the cause? If not I'll debug this. This is bother me for quite sometime

Animation

**Comment by AbhimanyuAryan** [comment]
could be a CSS issue maybe? 💭

**Comment by hhaensel** [comment]
This happens if the binding is not correct. Make sure that the slider has a field to bind to.

**Comment by AbhimanyuAryan** [comment]
> This happens if the binding is not correct. Make sure that the slider has a field to bind to. So in the above example make sure to add `@in betrange = 1`

I see. Let me check :)

**Pull request merged**
