### PR TITLE
code cleanup for lifecycle hooks 

### PR DESCRIPTION
**Pull request by AbhimanyuAryan**
please don't merge @hhaensel ❌

I haven't tested this

### CODE REVIEW

**Comment by AbhimanyuAryan** [comment]
tested looks ok ✅ @hhaensel if you think this is ok we can merge?

**Comment by hhaensel** [comment]
I had a short first check and it looks fine for me. I added very small changes. I think `Symbol` is better than `Meta.parse`, and in most of the macros we added `|> esc`  as a pipe to `quote end` so I sticked to that pattern.
Otherwise, I must say, I really like the style now. 👍

**Comment by AbhimanyuAryan** [comment]
@hhaensel just tested with a few examples. We should merge it. Looks good 

Screenshot 2023-03-20 at 2 02 57 PM

**Comment by hhaensel** [comment]
Agree!. Who's doing the merge?

**Comment by AbhimanyuAryan** [comment]
I can @hhaensel

**Pull request merged**
