### PR TITLE
fix deps loading for multi-page apps

### PR DESCRIPTION
**Pull request by hhaensel**
This is a tentative version for model-dependent deps-loading.

Not sure whether this is breaking. The idea is along the lines of what I described in #104.

Maybe we need to allow for "Strings" in DEPS keys for greater user flexibility?

### CODE REVIEW

**Comment by hhaensel** [comment]
Just realised that the DEPS type is indeed very strange:

```julia
const DEPS = OrderedCollections.OrderedDict{Union{Any, AbstractString}, Function}()
```
it used to be
```julia
const DEPS = OrderedCollections.OrderedDict{Union{Module, String}, Function}()
```
maybe we make it
```julia
const DEPS = OrderedCollections.OrderedDict{Union{Module, ReactiveType, String}, Function}()
```

**Comment by essenciary** [comment]
The problem was that I had situations where the deps were not tied to a module/package (to inject extra JS files to be used in the app). Why would we limit to modules anyway? Also `AbstractString` allows other types of strings. 
To be even more wide, we should probably make it `Union{<:Any,<:AbstractString}`. Can't see the point of restricting this - am I missing something?

**Comment by hhaensel** [comment]
I thought restricting could be interesting for compiler optimisations, but it's probably less important here. Why do you have a `Union{}` in that case at all and not just `OrderedDict{Any, Function}`?

**Comment by essenciary** [comment]
That's right =))

**Pull request merged**
