### PR TITLE
support for multipage app with different models/modules

### PR DESCRIPTION
**Pull request by AbhimanyuAryan**
don't merge ❌ fixing

### CODE REVIEW

**Comment by AbhimanyuAryan** [comment]
Here the app you can test @hhaensel @essenciary : https://github.com/AbhimanyuAryan/tabapp

```
pkg> add Stipple#branch
```
and then

```
using GenieFramework
Genie.loadapp()
up()
```

**Comment by AbhimanyuAryan** [comment]
looks like this. Any suggestions on improving API? 


```julia
module App

using GenieFramework
@genietools

include("contact.jl")
import .Contact

include("home.jl")
import .Home

Genie.Renderers.Html.register_normal_element(:marquee)

@page("/", "home.jl.html", Main.App.Home)
@page("/about", "about.jl.html", Main.App.Home)
@page("/contact", "contact.jl.html", Main.App.Contact)
end
```

**Comment by AbhimanyuAryan** [comment]
or can be used in global scope

`app.jl`
```julia
include("market.jl")
import .Market

module App

using GenieFramework
@genietools

include("contact.jl")
import .Contact

include("home.jl")
import .Home

Genie.Renderers.Html.register_normal_element(:marquee)

@page("/", "home.jl.html", Main.App.Home)
@page("/about", "about.jl.html", Main.App.Home)
@page("/contact", "contact.jl.html", Main.App.Contact)

end

@page("/market", "market.jl.html", Main.Market)
```

**Comment by hhaensel** [comment]
Wouldn't it be better to adapt Stipple.Pages.Page?
```julia
<...>
                model::Union{M,Function,Nothing,Expr,Module} = Stipple.init(EmptyModel),
<...>
  if isa(model, Expr)
    model = Core.eval(context, model)
  elseif isa(model, Module)
    context = model
    model = @eval(context, @init())
  end
```

**Comment by hhaensel** [comment]
That would allow for both usage with model types and modules, e.g.
```julia
@app Contact begin
    @in hh = "reach out for me via genie@work.com"
end

@app Home begin
    @in status = "My home is my castle"
end

@page("/", "home.jl.html", Home)
@page("/contact", "contact.jl.html", Contact)
```

**Comment by essenciary** [comment]
I think it's a great idea

**Comment by AbhimanyuAryan** [comment]
@hhaensel yes this is better I was trying keyword arguments with `@page` but the multiple dispatch not working with macros is a pain point. It's very difficult to achieve that without modifying public API

**Comment by AbhimanyuAryan** [comment]
@hhaensel sorry you meant this right?

```
@page("/", "home.jl.html", Stipple.ReactiveTools.DEFAULT_LAYOUT(), Main.App.Home)
@page("/about", "about.jl.html", Stipple.ReactiveTools.DEFAULT_LAYOUT(), Main.App.Home)
@page("/contact", "contact.jl.html", Stipple.ReactiveTools.DEFAULT_LAYOUT(), Main.App.Contact)
```

because of the same reason macros don't multiple dispatch

**Comment by essenciary** [comment]
@hhaensel if the 4th argument is a model, shouldn't we use the model's module as the default context, instead of the macro's invocation module? 

```julia
if isa(model, Expr)
    context = <module of model>
    model = Core.eval(context, model)
  elseif isa(model, Module)
    context = model
    model = @eval(context, @init())
  end
```

**Comment by AbhimanyuAryan** [comment]
@hhaensel looks like the current change broke the existing `@page` i.e. `@page("/", "app.jl.html)`. I am not sure where is `page` method called in this entire process. So only the macro with 4 args works which takes Module name.

```
Loading app(url, view, layout, model, context) = [ Info: 2023-06-15 00:19:47 Watching ["/Users/abhi/Downloads/tabapp"]
[ Info: 2023-06-15 00:19:47 Watching ["/Users/abhi/Downloads/tabapp"]
[ Info: 2023-06-15 00:19:47 Watching ["/Users/abhi/Downloads/tabapp"]
("/", "home.jl.html", :(Stipple.ReactiveTools.DEFAULT_LAYOUT()), :(()->begin
          #= /Users/abhi/.julia/dev/Stipple/src/ReactiveTools.jl:940 =#
          #= /Users/abhi/.julia/dev/Stipple/src/ReactiveTools.jl:940 =# @eval Main.App.Home #= /Users/abhi/.julia/dev/Stipple/src/ReactiveTools.jl:940 =# @init()
      end), Main.App.Home)

Ready!

┌ Info: 2023-06-15 00:19:48
└ Web Server starting at http://127.0.0.1:8000 - press Ctrl/Cmd+C to stop the server.
[ Info: 2023-06-15 00:19:49 Listening on: 127.0.0.1:8000, thread id: 1
┌ Error: 2023-06-15 00:19:57 MethodError: no method matching page(::Nothing, ::Vector{String}; partial::Bool, v__cloak::Bool, v-if::String)
│
│ Closest candidates are:
│   page(!Matched::M, ::Any...; partial, title, class, style, channel, head_content, prepend, append, core_theme, kwargs...) where M<:ReactiveModel
│    @ Stipple ~/.julia/dev/Stipple/src/Layout.jl:84
│
│ Stacktrace:
│   [1] (::Main.App.Home.var"#34#47"{Nothing})()
│     @ Main.App.Home /var/folders/0j/d0xd373d2tb7zdzcsqrk3mpw0000gn/T/jl_genie_build_TC8yMZ/GenieViews/0a8afd2e89521e6480eb6d1c4bffaaead7ca1be0.jl:57
│   [2] #invokelatest#2
│     @ ./essentials.jl:816 [inlined]
│   [3] invokelatest
│     @ ./essentials.jl:813 [inlined]
│   [4] normal_element(f::Function, elem::String, args::Vector{Any}, attrs::Vector{Pair{Symbol, Any}})
│     @ Genie.Renderer.Html ~/.julia/packages/Genie/XpFvB/src/renderers/Html.jl:137
│   [5] div(::Function; attrs::Base.Pairs{Symbol, String, Tuple{Symbol, Symbol}, NamedTuple{(:class, :htmlsourceindent), Tuple{String, String}}})
│     @ Genie.Renderer.Html ./none:2
│   [6] div
│     @ ./none:1 [inlined]
│   [7] (::Main.App.Home.var"#33#46"{Nothing})()
│     @ Main.App.Home /var/folders/0j/d0xd373d2tb7zdzcsqrk3mpw0000gn/T/jl_genie_build_TC8yMZ/GenieViews/0a8afd2e89521e6480eb6d1c4bffaaead7ca1be0.jl:56
│   [8] #invokelatest#2
│     @ ./essentials.jl:816 [inlined]
│   [9] invokelatest
│     @ ./essentials.jl:813 [inlined]
│  [10] normal_element(f::Function, elem::String, args::Vector{Any}, attrs::Vector{Pair{Symbol, Any}})
│     @ Genie.Renderer.Html ~/.julia/packages/Genie/XpFvB/src/renderers/Html.jl:137
│  [11] div(::Function; attrs::Base.Pairs{Symbol, String, Tuple{Symbol, Symbol}, NamedTuple{(:class, :htmlsourceindent), Tuple{String, String}}})
│     @ Genie.Renderer.Html ./none:2
│  [12] div
│     @ ./none:1 [inlined]
│  [13] (::Main.App.Home.var"#32#45"{Nothing})()
│     @ Main.App.Home /var/folders/0j/d0xd373d2tb7zdzcsqrk3mpw0000gn/T/jl_genie_build_TC8yMZ/GenieViews/0a8afd2e89521e6480eb6d1c4bffaaead7ca1be0.jl:55
│  [14] #invokelatest#2
│     @ ./essentials.jl:816 [inlined]
│  [15] invokelatest
│     @ ./essentials.jl:813 [inlined]
│  [16] normal_element(f::Function, elem::String, args::Vector{Any}, attrs::Vector{Pair{Symbol, Any}})
│     @ Genie.Renderer.Html ~/.julia/packages/Genie/XpFvB/src/renderers/Html.jl:137
│  [17] div(::Function; attrs::Base.Pairs{Symbol, String, Tuple{Symbol, Symbol}, NamedTuple{(:class, :htmlsourceindent), Tuple{String, String}}})
│     @ Genie.Renderer.Html ./none:2
│  [18] div
│     @ ./none:1 [inlined]
│  [19] (::Main.App.Home.var"#31#44"{Nothing})()
│     @ Main.App.Home /var/folders/0j/d0xd373d2tb7zdzcsqrk3mpw0000gn/T/jl_genie_build_TC8yMZ/GenieViews/0a8afd2e89521e6480eb6d1c4bffaaead7ca1be0.jl:54
│  [20] #invokelatest#2
│     @ ./essentials.jl:816 [inlined]
│  [21] invokelatest
│     @ ./essentials.jl:813 [inlined]
│  [22] normal_element(f::Function, elem::String, args::Vector{Any}, attrs::Vector{Pair{Symbol, Any}})
│     @ Genie.Renderer.Html ~/.julia/packages/Genie/XpFvB/src/renderers/Html.jl:137
│  [23] #body#79
│     @ ./none:2 [inlined]
│  [24] (::Main.App.Home.var"#27#40"{Nothing})()
│     @ Main.App.Home /var/folders/0j/d0xd373d2tb7zdzcsqrk3mpw0000gn/T/jl_genie_build_TC8yMZ/GenieViews/0a8afd2e89521e6480eb6d1c4bffaaead7ca1be0.jl:9
│  [25] #invokelatest#2
│     @ ./essentials.jl:816 [inlined]
│  [26] invokelatest
│     @ ./essentials.jl:813 [inlined]
│  [27] normal_element(f::Function, elem::String, args::Vector{Any}, attrs::Vector{Pair{Symbol, Any}})
│     @ Genie.Renderer.Html ~/.julia/packages/Genie/XpFvB/src/renderers/Html.jl:137
│  [28] #html#67
│     @ ./none:2 [inlined]
│  [29] func_dc62313a223e3efee34ace15d322d1682a5cd84f(; context::Module, model::Nothing)
│     @ Main.App.Home /var/folders/0j/d0xd373d2tb7zdzcsqrk3mpw0000gn/T/jl_genie_build_TC8yMZ/GenieViews/0a8afd2e89521e6480eb6d1c4bffaaead7ca1be0.jl:5
│  [30] func_dc62313a223e3efee34ace15d322d1682a5cd84f()
│     @ Main.App.Home /var/folders/0j/d0xd373d2tb7zdzcsqrk3mpw0000gn/T/jl_genie_build_TC8yMZ/GenieViews/0a8afd2e89521e6480eb6d1c4bffaaead7ca1be0.jl:3
│  [31] #invokelatest#2
│     @ ./essentials.jl:816 [inlined]
│  [32] invokelatest
│     @ ./essentials.jl:813 [inlined]
│  [33] WebRenderable(::Function)
│     @ Genie.Renderer ~/.julia/packages/Genie/XpFvB/src/Renderer.jl:163
│  [34] |>
│     @ ./operators.jl:907 [inlined]
│  [35] render(::Type{MIME{Symbol("text/html")}}, viewfile::FilePathsBase.PosixPath; layout::String, context::Module, vars::Base.Pairs{Symbol, Nothing, Tuple{Symbol}, NamedTuple{(:model,), Tuple{Nothing}}})
│     @ Genie.Renderer.Html ~/.julia/packages/Genie/XpFvB/src/renderers/Html.jl:486
│  [36] render
│     @ ~/.julia/packages/Genie/XpFvB/src/renderers/Html.jl:482 [inlined]
│  [37] #html#33
│     @ ~/.julia/packages/Genie/XpFvB/src/renderers/Html.jl:637 [inlined]
│  [38] (::Stipple.Pages.var"#5#6"{FilePathsBase.PosixPath, Nothing, String, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}})()
│     @ Stipple.Pages ~/.julia/dev/Stipple/src/Pages.jl:58
│  [39] run_route(r::Genie.Router.Route)
│     @ Genie.Router ~/.julia/packages/Genie/XpFvB/src/Router.jl:535
│  [40] route_request(req::HTTP.Messages.Request, res::HTTP.Messages.Response)
│     @ Genie.Router ~/.julia/packages/Genie/XpFvB/src/Router.jl:171
│  [41] handle_request(req::HTTP.Messages.Request, res::HTTP.Messages.Response)
│     @ Genie.Server ~/.julia/packages/Genie/XpFvB/src/Server.jl:278
│  [42] (::Genie.Server.var"#29#30"{HTTP.Messages.Request, HTTP.Messages.Response})()
│     @ Genie.Server ~/.julia/juliaup/julia-1.9.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/Distributed/src/macros.jl:123
│  [43] #invokelatest#2
│     @ ./essentials.jl:816 [inlined]
│  [44] invokelatest
│     @ ./essentials.jl:813 [inlined]
│  [45] #153
│     @ ~/.julia/juliaup/julia-1.9.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:425 [inlined]
│  [46] run_work_thunk(thunk::Distributed.var"#153#154"{Genie.Server.var"#29#30"{HTTP.Messages.Request, HTTP.Messages.Response}, Tuple{}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}, print_error::Bool)
│     @ Distributed ~/.julia/juliaup/julia-1.9.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/Distributed/src/process_messages.jl:70
│  [47] #remotecall_fetch#158
│     @ ~/.julia/juliaup/julia-1.9.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:450 [inlined]
│  [48] remotecall_fetch
│     @ ~/.julia/juliaup/julia-1.9.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:449 [inlined]
│  [49] #remotecall_fetch#162
│     @ ~/.julia/juliaup/julia-1.9.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:492 [inlined]
│  [50] remotecall_fetch
│     @ ~/.julia/juliaup/julia-1.9.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:492 [inlined]
│  [51] setup_http_listener(req::HTTP.Messages.Request, res::HTTP.Messages.Response)
│     @ Genie.Server ~/.julia/packages/Genie/XpFvB/src/Server.jl:305
│  [52] setup_http_listener
│     @ ~/.julia/packages/Genie/XpFvB/src/Server.jl:304 [inlined]
│  [53] (::HTTP.Handlers.var"#1#2"{typeof(Genie.Server.setup_http_listener)})(stream::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}})
│     @ HTTP.Handlers ~/.julia/packages/HTTP/uAaAw/src/Handlers.jl:58
│  [54] setup_http_streamer(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}})
│     @ Genie.Server ~/.julia/packages/Genie/XpFvB/src/Server.jl:294
│  [55] (::Genie.Server.var"#7#14")(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}})
│     @ Genie.Server ~/.julia/packages/Genie/XpFvB/src/Server.jl:121
│  [56] #invokelatest#2
│     @ ./essentials.jl:816 [inlined]
│  [57] invokelatest
│     @ ./essentials.jl:813 [inlined]
│  [58] handle_connection(f::Function, c::HTTP.Connections.Connection{Sockets.TCPSocket}, listener::HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, readtimeout::Int64, access_log::Nothing)
│     @ HTTP.Servers ~/.julia/packages/HTTP/uAaAw/src/Servers.jl:447
│  [59] macro expansion
│     @ ~/.julia/packages/HTTP/uAaAw/src/Servers.jl:385 [inlined]
│
└ @ Genie.Server ~/.julia/packages/Genie/XpFvB/src/Server.jl:317
```

**Comment by essenciary** [comment]
> That's a good idea, but how would we get the context. I think you only get it from where the module is called, and that's what currently happens, right?

The `@which` macro could do the trick: 

```julia
julia> module TestM
       const X = 20
       end
Main.TestM

julia> using .TestM

julia> @which TestM.X
Main.TestM
```

**Comment by essenciary** [comment]
@AbhimanyuAryan it's the `Layout.page` function which expects a model as its first argument. The error is telling you that you're sending `Nothing` instead of an instance of a module.

**Comment by AbhimanyuAryan** [comment]
indeed it was only checking Expr and Module. Not type `M`

**Comment by hhaensel** [comment]
> @AbhimanyuAryan it's the `Layout.page` function which expects a model as its first argument. The error is telling you that you're sending `Nothing` instead of an instance of a model.
> 
> Most likely this is due to the fact that you have `if ... / elseif ...` and if the type doesn't match any of these, then `model` is set to `Nothing`. So you also need an `else model`

My bad, sorry!

**Comment by AbhimanyuAryan** [comment]
> > @AbhimanyuAryan it's the `Layout.page` function which expects a model as its first argument. The error is telling you that you're sending `Nothing` instead of an instance of a model.
> > 
> > Most likely this is due to the fact that you have `if ... / elseif ...` and if the type doesn't match any of these, then `model` is set to `Nothing`. So you also need an `else model`
> 
> My bad, sorry!

no problem

**Comment by essenciary** [comment]
@AbhimanyuAryan Can this be merged?

**Pull request merged**
