### PR TITLE
Native event handlers

### PR DESCRIPTION
**Pull request by wildart**
Currently events are only trigger a JavaScript code provided in `v-on:*` attribute. This PR prvides a simple callback mechanism for a Julia function associated with an `v-on:*` event using same web channel used for communicating changes between a model and a view.

The native event handlers defined as overrides of `Base.notify` with two parameters a model object and a value type which contains a name of the event, e.g. `notify(model::TestModel, ::Val{:button_click})`.

The following example shows a definition of an event handler function and its wiring with `@on` macro to a button. 

```julia
module JuliaEvents

using Revise
using Stipple, StippleUI

@reactive! mutable struct TestModel <: ReactiveModel
  counter::R{Int} = 0
end

# Event handler
function Base.notify(model::TestModel, ::Val{:button_click})
    @info "Button Click Event"
    model.counter[] += 1
end

function ui(model::TestModel)
    page(model, 
        row(class = "st-module", [
            cell([
                "Counter: "
                span("", @text(:counter))
            ]),
            cell([
                # wire 'click' event to the handler
                btn("Click me", @on(:click, :button_click)) 
            ])
        ])
    )
end

route("/") do
    init(TestModel) |> ui |> html
end

up(8000)

end 
```

### CODE REVIEW

**Comment by essenciary** [comment]
@wildart this is awesome, thanks so much! 
@hhaensel as the expert on JS integration, do you want to review and merge?

**Comment by hhaensel** [comment]
I couldn't fi d the time for proper reviewing yet.
But on the first view from my mobile it does look ok. It's a really cool feature.

**Comment by essenciary** [comment]
@wildart I want to merge this but the behaviour does not seem to be documented anywhere. Can you please add/extend the docs for the `@on` macro?

**Comment by hhaensel** [comment]
@wildart Thanks again for your contribution. I modified your handler to also submit event information. Furthermore, when loading ReactiveTools you can also do.

```julia
@event :click begin
    @info "Hello World"
    model.message[] = "We've received the following event: \n" * repr(event)
end
```
So now, `Base.notify()` is called with three arguments; `model`, `handler` and `event`. But I keep triggering a two-argument method  ,if there is one, for compatibility reasons. I hope you like it. Here's a short [demo snippet](https://discourse.julialang.org/t/announcing-genie-builder-a-no-code-plugin-to-quickly-build-web-guis-dashboards/84643/32?u=hhaensel).

**Pull request merged**
