### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by yakir12**
Bumped Observables to 0.4

### CODE REVIEW

**Comment by hhaensel** [comment]
Is there something urgent about the release 0.4 of Observables?

**Comment by yakir12** [comment]
I was under the (wrong) impression that `ObserverFunction` was a 0.4 thing, but I was wrong.

**Comment by hhaensel** [comment]
So we will rather make it `[0.3, 0.4]`

**Comment by yakir12** [comment]
That is wise (although, checkout my warning on discord: https://discord.com/channels/774897545717219328/774897848718327818/815539886424850452)

**Pull request merged**
