### PR TITLE
migrate from JSON to JSON3

### LINKED ISSUE #59: Migrate from JSON.jl to JSON3.jl
@essenciary After you have nicely moved all JSON code in Genie to JSON3, we could think about doing the same for Stipple.
Here are my 2 cents to it; define a JSONText equivalent in JSON3.
```
using JSON3, StructTypes

struct JSONText
    s::String
end

@inline StructTypes.StructType(::Type{JSONText}) = JSON3.RawType()
@inline StructTypes.construct(::Type{JSONText}, x::JSON3.RawValue) = JSONText(string(x))
@inline JSON3.rawbytes(x::JSONText) = x.s
```
All `JSON.lower` definitions would then need to be replaced by `JSON3.rawbytes()` plus the StructType definition, if I got it right.

### PR DESCRIPTION
**Pull request by hhaensel**
This PR tries to fix #59.

Documentation is not yet changed.

`JSON.lower` should be replaced by `@json lower`

### CODE REVIEW

**Comment by essenciary** [comment]
@hhaensel Thank you - please allow me to run some extensive tests on the branch. I'll follow up ASAP (end of today if possible).

**Comment by hhaensel** [comment]
We should adapt the docs within this PR.
We have some html pages which include explanatory info on JSON.lower which also needs modification

**Comment by hhaensel** [comment]
@essenciary did you find time for testing? If everything is ok, I'd change the docs.

**Comment by essenciary** [comment]
@hhaensel Seems to work fine but there is a warning I don't fully understand: 

image

**Pull request merged**
